USE [master]
GO

/****** Object:  Database [iMessage]    Script Date: 15.04.2018 22:49:00 ******/
CREATE DATABASE [iMessage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'iMessage', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\iMessage.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'iMessage_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\iMessage_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [iMessage] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iMessage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iMessage] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iMessage] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iMessage] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iMessage] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iMessage] SET ARITHABORT OFF 
GO

ALTER DATABASE [iMessage] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iMessage] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [iMessage] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iMessage] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iMessage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iMessage] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iMessage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iMessage] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iMessage] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iMessage] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iMessage] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iMessage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iMessage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iMessage] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iMessage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iMessage] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iMessage] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iMessage] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iMessage] SET RECOVERY FULL 
GO

ALTER DATABASE [iMessage] SET  MULTI_USER 
GO

ALTER DATABASE [iMessage] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iMessage] SET DB_CHAINING OFF 
GO

ALTER DATABASE [iMessage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [iMessage] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [iMessage] SET  READ_WRITE 
GO

